image: "rust:latest"

check:
  script:
    - rustc --version && cargo --version
    - cargo check
test:
  needs: ["check"]
  script:
    - cargo test
build:
  needs: ["test"]
  script:
    - cargo build
