image: "rust:latest"

check:
  script:
    - rustc --version && cargo --version
    - cargo check
test:
  needs: ["check"]
  script:
    - cargo tests
build:
  needs: ["test"]
  script:
    - cargo build
